FROM scratch
LABEL org.opencontainers.image.source=https://github.com/aicacia/rs-auth

WORKDIR /app

ARG TARGET=x86_64-unknown-linux-musl
COPY target/${TARGET}/release/auth /app/auth

ENV RUN_MODE=production

CMD ["/app/auth", "-c", "/app/config.json"]
