FROM rust:1.73-bookworm as builder

RUN apt update && apt -yq upgrade
RUN apt -yq install libpq-dev

WORKDIR /
RUN cargo new app
WORKDIR /app

COPY Cargo.toml Cargo.lock ./
RUN cargo build --release

COPY . .
RUN cargo install --path .

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /usr/local/cargo/bin/auth /usr/local/bin

ENV RUN_MODE=production

CMD ["auth"]
