FROM alpine:3.22
LABEL org.opencontainers.image.source=https://github.com/aicacia/rs-auth

WORKDIR /app

ARG TARGET=x86_64-unknown-linux-musl
COPY ./target/${TARGET}/release/auth /usr/local/bin

ENV RUN_MODE=production

CMD ["auth", "-c", "/app/config.json"]
