DROP TABLE IF EXISTS "key_values" CASCADE;

DROP TABLE IF EXISTS "user_oauth2_providers" CASCADE;
DROP TABLE IF EXISTS "user_phone_numbers" CASCADE;
DROP TABLE IF EXISTS "user_emails" CASCADE;
DROP TABLE IF EXISTS "user_totps" CASCADE;
DROP TABLE IF EXISTS "user_passwords" CASCADE;
DROP TABLE IF EXISTS "user_infos" CASCADE;
DROP TABLE IF EXISTS "user_configs" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS "service_accounts" CASCADE;

DROP TABLE IF EXISTS "tenant_oauth2_providers" CASCADE;
DROP TABLE IF EXISTS "tenants" CASCADE;

DROP TABLE IF EXISTS "applications" CASCADE;