/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserPhoneNumber {
    #[serde(rename = "phone_number")]
    pub phone_number: String,
}

impl CreateUserPhoneNumber {
    pub fn new(phone_number: String) -> CreateUserPhoneNumber {
        CreateUserPhoneNumber {
            phone_number,
        }
    }
}

