/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserEmail {
    #[serde(rename = "email")]
    pub email: String,
}

impl CreateUserEmail {
    pub fn new(email: String) -> CreateUserEmail {
        CreateUserEmail {
            email,
        }
    }
}

