/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUser {
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(rename = "username")]
    pub username: String,
}

impl CreateUser {
    pub fn new(active: bool, username: String) -> CreateUser {
        CreateUser {
            active,
            username,
        }
    }
}

