/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwtRequest {
    #[serde(rename = "claims")]
    pub claims: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "tenant_id")]
    pub tenant_id: i64,
}

impl JwtRequest {
    pub fn new(claims: std::collections::HashMap<String, serde_json::Value>, tenant_id: i64) -> JwtRequest {
        JwtRequest {
            claims,
            tenant_id,
        }
    }
}

