/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MfaRequest {
    MfaRequestTotp(models::MfaRequestTotp),
    MfaRequestServiceAccount(models::MfaRequestServiceAccount),
}

impl Default for MfaRequest {
    fn default() -> Self {
        Self::MfaRequestTotp(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "totp")]
    Totp,
    #[serde(rename = "service-account")]
    ServiceAccount,
}

impl Default for Type {
    fn default() -> Type {
        Self::Totp
    }
}

