/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterUser {
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "password_confirmation")]
    pub password_confirmation: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl RegisterUser {
    pub fn new(password: String, password_confirmation: String, username: String) -> RegisterUser {
        RegisterUser {
            password,
            password_confirmation,
            username,
        }
    }
}

