/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResetPasswordRequest {
    #[serde(rename = "current_password")]
    pub current_password: String,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "password_confirmation")]
    pub password_confirmation: String,
}

impl ResetPasswordRequest {
    pub fn new(current_password: String, password: String, password_confirmation: String) -> ResetPasswordRequest {
        ResetPasswordRequest {
            current_password,
            password,
            password_confirmation,
        }
    }
}

