/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenRequestOneOf {
    #[serde(rename = "grant_type")]
    pub grant_type: GrantType,
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "scope", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scope: Option<Option<String>>,
    #[serde(rename = "username")]
    pub username: String,
}

impl TokenRequestOneOf {
    pub fn new(grant_type: GrantType, password: String, username: String) -> TokenRequestOneOf {
        TokenRequestOneOf {
            grant_type,
            password,
            scope: None,
            username,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GrantType {
    #[serde(rename = "password")]
    Password,
}

impl Default for GrantType {
    fn default() -> GrantType {
        Self::Password
    }
}

