/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserConfigRequest {
    #[serde(rename = "mfa_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mfa_type: Option<Option<models::UserMfaType>>,
}

impl UpdateUserConfigRequest {
    pub fn new() -> UpdateUserConfigRequest {
        UpdateUserConfigRequest {
            mfa_type: None,
        }
    }
}

