/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPhoneNumber {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "phone_number")]
    pub phone_number: String,
    #[serde(rename = "primary")]
    pub primary: bool,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "verified")]
    pub verified: bool,
}

impl UserPhoneNumber {
    pub fn new(created_at: String, id: i64, phone_number: String, primary: bool, updated_at: String, verified: bool) -> UserPhoneNumber {
        UserPhoneNumber {
            created_at,
            id,
            phone_number,
            primary,
            updated_at,
            verified,
        }
    }
}

