/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;
use std::borrow::Borrow;
use std::pin::Pin;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use hyper_util::client::legacy::connect::Connect;
use futures::Future;

use crate::models;
use super::{Error, configuration};
use super::request as __internal_request;

pub struct MfaApiClient<C: Connect>
    where C: Clone + std::marker::Send + Sync + 'static {
    configuration: Arc<configuration::Configuration<C>>,
}

impl<C: Connect> MfaApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    pub fn new(configuration: Arc<configuration::Configuration<C>>) -> MfaApiClient<C> {
        MfaApiClient {
            configuration,
        }
    }
}

pub trait MfaApi: Send + Sync {
    fn mfa(&self, mfa_request: models::MfaRequest) -> Pin<Box<dyn Future<Output = Result<models::Token, Error>> + Send>>;
}

impl<C: Connect>MfaApi for MfaApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    #[allow(unused_mut)]
    fn mfa(&self, mfa_request: models::MfaRequest) -> Pin<Box<dyn Future<Output = Result<models::Token, Error>> + Send>> {
        let mut req = __internal_request::Request::new(hyper::Method::POST, "/mfa".to_string())
        ;
        req = req.with_body_param(mfa_request);

        req.execute(self.configuration.borrow())
    }

}
