/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;
use std::borrow::Borrow;
use std::pin::Pin;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use hyper_util::client::legacy::connect::Connect;
use futures::Future;

use crate::models;
use super::{Error, configuration};
use super::request as __internal_request;

pub struct RegisterApiClient<C: Connect>
    where C: Clone + std::marker::Send + Sync + 'static {
    configuration: Arc<configuration::Configuration<C>>,
}

impl<C: Connect> RegisterApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    pub fn new(configuration: Arc<configuration::Configuration<C>>) -> RegisterApiClient<C> {
        RegisterApiClient {
            configuration,
        }
    }
}

pub trait RegisterApi: Send + Sync {
    fn register_user(&self, register_user: models::RegisterUser) -> Pin<Box<dyn Future<Output = Result<models::Token, Error>> + Send>>;
}

impl<C: Connect>RegisterApi for RegisterApiClient<C>
    where C: Clone + std::marker::Send + Sync {
    #[allow(unused_mut)]
    fn register_user(&self, register_user: models::RegisterUser) -> Pin<Box<dyn Future<Output = Result<models::Token, Error>> + Send>> {
        let mut req = __internal_request::Request::new(hyper::Method::POST, "/register".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "Tenant-ID".to_owned(),
            }))
        ;
        req = req.with_body_param(register_user);

        req.execute(self.configuration.borrow())
    }

}
