/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenRequestOneOf1 {
    #[serde(rename = "grant_type")]
    pub grant_type: GrantType,
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
}

impl TokenRequestOneOf1 {
    pub fn new(grant_type: GrantType, refresh_token: String) -> TokenRequestOneOf1 {
        TokenRequestOneOf1 {
            grant_type,
            refresh_token,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GrantType {
    #[serde(rename = "refresh-token")]
    RefreshToken,
}

impl Default for GrantType {
    fn default() -> GrantType {
        Self::RefreshToken
    }
}

