/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserMfaType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "totp")]
    Totp,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "text")]
    Text,

}

impl std::fmt::Display for UserMfaType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::Totp => write!(f, "totp"),
            Self::Email => write!(f, "email"),
            Self::Text => write!(f, "text"),
        }
    }
}

impl Default for UserMfaType {
    fn default() -> UserMfaType {
        Self::None
    }
}

