/*
 * auth
 *
 * Aicacia Auth API provides authentication services for applications.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserResetPassword {
    #[serde(rename = "scope", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scope: Option<Option<String>>,
    #[serde(rename = "tenant_id")]
    pub tenant_id: i64,
}

impl UserResetPassword {
    pub fn new(tenant_id: i64) -> UserResetPassword {
        UserResetPassword {
            scope: None,
            tenant_id,
        }
    }
}

